name: Compiler Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Static Analysis (SonarCloud)
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # CRITICAL: SonarCloud needs the full git history

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Sandheep-S-95_SyntaxForge-Compiler
            -Dsonar.organization=sandheep-s-95
            -Dsonar.sources=.
            -Dsonar.inclusions=*.cpp,*.h
            -Dsonar.exclusions=tests/**,build/**

  # 2. Build and Test Natively
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build
        run: g++ compiler.cpp -std=c++17 -o compiler

      - name: Run Tests (Linux Native)
        run: |
          echo "Running valid test..."
          cp tests/valid_1.txt input.txt
          ./compiler
          
          echo "Running invalid test..."
          cp tests/invalid_1.txt input.txt
          # Adding '|| true' so the pipeline doesn't crash if your invalid test intentionally throws an error!
          ./compiler || true 

  # 3. Docker Build & Push (Only runs if tests pass)
  docker-publish:
    needs: [test, quality-checks]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/earley-compiler:latest,${{ secrets.DOCKERHUB_USERNAME }}/earley-compiler:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/earley-compiler:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/earley-compiler:buildcache,mode=max

            # -Dsonar.projectKey=Sandheep-S-95_SyntaxForge-Compiler
            # -Dsonar.organization=sandheep-s-95